from typing import List

class Solution:
    def maxArea(self, height: List[int]) -> int:
        maxArea = 0
        left = 0
        right = len(height) - 1
        while left < right:
            width = right - left
            min_height = min(height[left], height[right])
            area = min_height * width
            maxArea = max(maxArea, area)
            if height[left] < height[right]:
                left += 1
            else:
                right -= 1
        return maxArea

# Example usage:
# height = [1, 8, 6, 2, 5, 4, 8, 3, 7]
# print(Solution().maxArea(height))
